### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by Cascadence** [vkuznecovas/mouthful#111]
I'm quite new to the back end, and am hoping for some direction. Forgive me if my issues seem elementary.

I am trying to get a working instance under XAMPP, and performed the following: 

1) Unpacked the Windows archive to a folder inside `htdocs` called `mouthful`, and created an HTML file with the provided markup:

    ```
    <div id="mouthful-comments" data-url="http://localhost:8080"</div>
    <script src="http://localhost:8080/client.js"></script>
    ```

2) Since XAMPP is running Apache and MySQL, I used the provided sample MySQL config file code, and copied it to  `config.json` in the `data` dir. I configured it according to direction (or so I thought) as follows:

```
{
    "honeypot": true,
    "moderation": {
        "enabled": true,
        "adminPassword": "--modpassword--",
        "sessionDurationSeconds": 21600,
        "maxCommentLength": 10000,
        "maxAuthorLength": 35
    },
    "database": {
        "dialect": "mysql",
        "database": "mouthful",
        "host": "localhost",
        "username": "mouthful_user",
        "password": "--dbpassword--",
        "port": "3306"
    },
    "api": {
        "port": 8080,
        "logging": true,
        "debug": false,
        "cache": {
            "enabled": true,
            "intervalInSeconds": 10,
            "expiryInSeconds": 300
        },
        "rateLimiting": {
            "enabled": true,
            "postsHour": 100
        },

        "cors": {
            "enabled": false,
            "allowedOrigins": ["http://localhost:8080"]
        }
    },
    "client": {
        "useDefaultStyle": true,
        "pageSize": 10
    }
}
```
I have tried several variations of this config; with both `moderation` and `cors` enabled/disabled, but each time I try running `mouthful.exe` from the XAMPP shell, the following is returned:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb5176c]

goroutine 1 [running]:
github.com/vkuznecovas/mouthful/vendor/github.com/jmoiron/sqlx.(*DB).MapperFunc(...)
        /home/travis/gopath/src/github.com/vkuznecovas/mouthful/vendor/github.com/jmoiron/sqlx/sqlx.go:277
github.com/vkuznecovas/mouthful/db/sqlxDriver/mysql.CreateDatabase(0xc04200ed60, 0x5, 0xc04202cb70, 0xc04202cb90, 0xc04202cba0, 0xc04202cb80, 0xc04202cbb0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/vkuznecovas/mouthful/db/sqlxDriver/mysql/mysql.go:73 +0x33c
github.com/vkuznecovas/mouthful/db.GetDBInstance(0xc04200ed60, 0x5, 0xc04202cb70, 0xc04202cb90, 0xc04202cba0, 0xc04202cb80, 0xc04202cbb0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/vkuznecovas/mouthful/db/db.go:26 +0x213
main.main()
        /home/travis/gopath/src/github.com/vkuznecovas/mouthful/main.go:59 +0x2c5
```
Last night, somehow I got mouthful running on the backend without any errors in the shell, but with the same issue as #91: The client page returning "The comments are temporarily unavailable", after which I adjusted the `cors` values (as suggest and which had worked for that user) by toggling enabled/disabled, and changing the `allowedOrigins` while enabled to `http://localhost:8080`, but to no avail in my case. I can't for the life of me remember what I did to make the binary run, but have since changed installation directories of the entire archive twice, thinking that somehow a path was missing due to my unpacking the archive into a new directory inside the `htdocs` dir, and now I cannot get mouthful to run without error again.

I'm also unsure of what, if anything, to do with the code given in the Nginx config example. I am thrown off by the statement:

> "In most cases, you'll want to run mouthful under nginx, or apache, or something else. In that case, this is the config I'm using for the demo: 

```
location /mouthful-demo/ {
            proxy_pass http://172.17.0.1:1224/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
	    add_header Cache-Control 'no-cache' always;
}
```
Does this mean because I am running Apache in XAMPP, I should be using this code, or some variation of it somewhere? I understand that it is a config example for Nginx, not Apache, but config of what? It doesn't belong in the `config.json` file, so does it mean that it belongs in the Apache `httpd.conf` file, and if so, where?

Any help will be appreciated.

**Comment by Cascadence** [comment]
Since there has been no replies, I gave up on trying to get this working within XAMPP and secured a VPS running Nginx and Postgres hoping I could get it working on my own. Now I'm running into a new problem: `panic: default addr for network 'localhost:5432' unknown`, so I'm closing out this issue and have opened #112. Fingers crossed; I'm really trying to learn.
