### ISSUE TITLE
Panic: default addr for network 'localhost:5432' unknown

### ISSUE THREAD

**Issue by Cascadence** [vkuznecovas/mouthful#112]
Since I wasn't able to figure out `
Panic: runtime error: invalid memory address or nil pointer dereference
` (#111), I went ahead and secured a VPS running Nginx and ProstgreSQL, and decided to try my luck there. No dice so far.

I am now encountering `panic: default addr for network 'localhost:5432' unknown`.

Here is my config file:

```
{
    "honeypot": true,
    "moderation": {
        "enabled": false,
        "adminPassword": "xxxxxxxxxx",
        "sessionDurationSeconds": 21600,
        "maxCommentLength": 10000,
        "maxAuthorLength": 35
    },
    "database": {
        "dialect": "postgres",
        "database": "mouthful",
        "host": "localhost",
        "username": "postgres",
        "password": "xxxxxxxxxxx",
        "port": "5432",
        "sslEnabled": false
    },
    "api": {
        "port": 8080,
        "logging": true,
        "debug": false,
        "cache": {
            "enabled": true,
            "intervalInSeconds": 10,
            "expiryInSeconds": 300
        },
        "rateLimiting": {
            "enabled": true,
            "postsHour": 100
        },
        "cors": {
            "enabled": true,
            "allowedOrigins": ["https://mydomain.com"]
        }
    },
    "client": {
        "useDefaultStyle": true,
        "pageSize": 10
    }
}
```
I've tried toggling sslEnabled, as the server block is configured to redirect to https anyway, but that didn't work, either.

I am still unsure of what the "Nginx config example" is for, where is goes, or what this quote means:

>"In most cases, you'll want to run mouthful under nginx, or apache, or something else. In that case, this is the config I'm using for the demo:

```
location /mouthful-demo/ {
            proxy_pass http://172.17.0.1:1224/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
	    add_header Cache-Control 'no-cache' always;
}
```
I noticed that Vik hasn't been active in over a year here, on his blog, or on Twitter, but if anyone else can help point me in the right direction, I'll be incredibly grateful!

**Comment by vkuznecovas** [comment]
Could you please try again with the latest master?

I've spotted an issue where the postgres connection was not formed correctly, passing in mysql instead.

See #113

**Comment by Cascadence** [comment]
Gave that a try, but wound up with errors.

First installed dependencies as required, each installation confirmed. Cloned master, ran `build.sh`, and got the following:

```
Current option settings
errexit         on
noglob          off
ignoreeof       off
interactive     off
monitor         off
noexec          off
stdin           off
xtrace          on
verbose         off
vi              off
emacs           off
noclobber       off
allexport       off
notify          off
nounset         on
priv            off
nolog           off
debug           off
+ rm -rf ./dist
+ mkdir -p ./dist
+ mkdir -p ./dist/static
+ mkdir -p ./dist/data
+ cd ./client
+ npm i

> simplehttp2server@2.0.0 postinstall /usr/local/mouthful/client/node_modules/si                                                                                                                                                             mplehttp2server
> node lib/install.js


> preact-cli@2.2.1 postinstall /usr/local/mouthful/client/node_modules/preact-cl                                                                                                                                                             i
> node -p 'require("./check.js")()'

true
npm WARN client@0.1.0 No description
npm WARN client@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/san                                                                                                                                                             e/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                             1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                                                                             )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/cho                                                                                                                                                             kidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                             1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                                                                             )

added 192 packages from 116 contributors and audited 1996 packages in 27.418s

3 packages are looking for funding
  run `npm fund` for details

found 2525 vulnerabilities (1320 low, 9 moderate, 1195 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
+ npm run build

> client@0.1.0 build /usr/local/mouthful/client
> preact build --no-prerender --clean --template src/index.ejs --service-worker                                                                                                                                                              false

✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js??ref--2-0!./sr                                                                                                                                                             c/components/client/style.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/usr/loc                                                                                                                                                             al/mouthful/client/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:982:3)
    at Object.getInstalledBinaries (/usr/local/mouthful/client/node_modules/node                                                                                                                                                             -sass/lib/extensions.js:133:13)
    at foundBinariesList (/usr/local/mouthful/client/node_modules/node-sass/lib/                                                                                                                                                             errors.js:20:15)
    at foundBinaries (/usr/local/mouthful/client/node_modules/node-sass/lib/erro                                                                                                                                                             rs.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/mouthful/client/node_modu                                                                                                                                                             les/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/mouthful/client/node_modules/node-sass/lib/bin                                                                                                                                                             ding.js:15:30)
    at Object.<anonymous> (/usr/local/mouthful/client/node_modules/node-sass/lib                                                                                                                                                             /index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/usr/local/mouthful/client                                                                                                                                                             /node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/mouthful/client/node_modules/sass-loader/l                                                                                                                                                             ib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
 @ ./src/components/client/style.scss 4:14-225
 @ ./src/components/client/index.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
Build failed! null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 build: `preact build --no-prerender --clean --template src                                                                                                                                                             /index.ejs --service-worker false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-22T23_11_32_883Z-debug.log
```

I'm guessing that there is a conflict of some sort between Mouthful and Node.js, which was installed using `curl` and `node -v` shows `v14.12.0`.

**Comment by vkuznecovas** [comment]
There was a bug with the postgres driver, closing it since it now is fixed.
